# Generated by Django 4.2.5 on 2023-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Di', 'Disabled'), ('Ac', 'Active')], default='Ac', max_length=2)),
                ('type', models.CharField(choices=[('Ad', 'Admin'), ('Cu', 'Customer'), ('St', 'Stuff')], default='Cu', max_length=2)),
            ],
            options={
                'ordering': ['-created_at', 'first_name', 'last_name'],
                'indexes': [models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx')],
            },
        ),
    ]
